FROM python:3
ENV DOCKER_CLIENT_TIMEOUT=120
ENV COMPOSE_HTTP_TIMEOUT=120
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

# copy entrypoint.sh
COPY ./entrypoint.prod.sh /code/entrypoint.prod.sh

# run entrypoint.sh
ENTRYPOINT ["/code/entrypoint.prod.sh"]

