# Generated by Django 2.2 on 2019-05-27 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changetype',
            fields=[
                ('changetypeid', models.AutoField(db_column='changeTypeId', primary_key=True, serialize=False)),
                ('changetypename', models.CharField(db_column='changeTypeName', max_length=50)),
                ('changetypeweight', models.IntegerField(db_column='changeTypeWeight', default=1)),
            ],
            options={
                'db_table': 'changeType',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationValue',
            fields=[
                ('configid', models.AutoField(db_column='configurationId', primary_key=True, serialize=False)),
                ('configname', models.CharField(max_length=50)),
                ('configvalue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='teamID', primary_key=True, serialize=False)),
                ('teamname', models.CharField(db_column='teamName', max_length=150)),
                ('teamemail', models.EmailField(db_column='teamEmail', max_length=200, unique=True)),
                ('created_on', models.DateTimeField(db_column='createdon', default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_column='isactive', default=True)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('joined_on', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover.Team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False, unique=True)),
                ('userfirstname', models.CharField(db_column='userFirstName', max_length=50)),
                ('userlastname', models.CharField(db_column='userLastName', max_length=50)),
                ('userpassword', models.CharField(db_column='userpassword', max_length=50)),
                ('useremail', models.EmailField(db_column='userEmail', max_length=150, unique=True)),
                ('userreputation', models.IntegerField(default=0)),
                ('basictraining', models.BooleanField(default=False)),
                ('usercreatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_logon', models.DateTimeField(blank=True, null=True)),
                ('user_is_active', models.BooleanField(default=True)),
                ('team', models.ManyToManyField(through='handover.Teammember', to='handover.Team')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover.User'),
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('handoverid', models.AutoField(db_column='handoverID', primary_key=True, serialize=False)),
                ('title', models.CharField(default='***This handover has no title***', max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('createdon', models.DateTimeField(db_column='createdOn', default=django.utils.timezone.now)),
                ('ticketno', models.IntegerField(blank=True, db_column='ticketNo', null=True)),
                ('checkedbyassignee', models.BooleanField(db_column='checkedByAssignee', default=False)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('severity', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Active'), (3, 'Resolved')], default=1)),
                ('assignedto', models.ForeignKey(blank=True, db_column='assignedTo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoverassignedto', to='handover.User')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoverreatedby', to='handover.User')),
                ('resolvedby', models.ForeignKey(blank=True, db_column='resolvedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoverresolvedby', to='handover.User')),
                ('spoc', models.ForeignKey(blank=True, db_column='spoc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoverspoc', to='handover.User')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handover.Team')),
            ],
            options={
                'db_table': 'Handover',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussionid', models.BigAutoField(db_column='discussionId', primary_key=True, serialize=False)),
                ('discussiontext', models.CharField(db_column='discussionText', max_length=100)),
                ('discussiontime', models.DateTimeField(db_column='discussionTime', default=django.utils.timezone.now)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.User')),
                ('handoverid', models.ForeignKey(db_column='handoverId', on_delete=django.db.models.deletion.CASCADE, to='handover.Handover')),
            ],
            options={
                'db_table': 'Discussion',
            },
        ),
        migrations.CreateModel(
            name='Changestable',
            fields=[
                ('changeid', models.BigAutoField(db_column='changeId', primary_key=True, serialize=False)),
                ('changedon', models.DateTimeField(db_column='changedOn', default=django.utils.timezone.now)),
                ('changecomment', models.CharField(db_column='changeComment', max_length=200, null=True)),
                ('changedby', models.ForeignKey(db_column='changedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.User')),
                ('changetypeid', models.ForeignKey(db_column='changeTypeId', on_delete=django.db.models.deletion.CASCADE, to='handover.Changetype')),
                ('handover', models.ForeignKey(db_column='handoverId', on_delete=django.db.models.deletion.CASCADE, to='handover.Handover')),
            ],
            options={
                'db_table': 'changesTable',
            },
        ),
    ]
