# Generated by Django 2.2 on 2019-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='person',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='user_id',
            new_name='user',
        ),
    ]
