# Generated by Django 2.2 on 2019-05-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0002_auto_20190527_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='changetypename',
            field=models.CharField(db_column='changeTypeName', max_length=50, unique=True),
        ),
    ]
