# Generated by Django 2.2 on 2019-06-03 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0003_auto_20190527_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
