# Generated by Django 2.2 on 2019-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0004_auto_20190603_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationvalue',
            name='configvalue',
            field=models.CharField(max_length=100),
        ),
    ]
