# Generated by Django 2.2 on 2019-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0006_auto_20190603_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlastname',
            field=models.CharField(blank=True, db_column='userLastName', max_length=50, null=True),
        ),
    ]
