# Generated by Django 2.2 on 2019-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0007_auto_20190603_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlastname',
            field=models.CharField(db_column='userLastName', default='', max_length=50),
        ),
    ]
