# Generated by Django 2.2 on 2019-06-05 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0009_auto_20190603_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logid', models.BigAutoField(db_column='logId', primary_key=True, serialize=False)),
                ('loggedon', models.DateTimeField(db_column='loggedOn', default=django.utils.timezone.now)),
                ('logcomment', models.CharField(db_column='logComment', max_length=200, null=True)),
                ('logged_by', models.ForeignKey(db_column='loggedByUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loggedbyuser', to='handover.User')),
                ('logtypeid', models.ForeignKey(db_column='logTypeId', on_delete=django.db.models.deletion.CASCADE, to='handover.Changetype')),
                ('related_team', models.ForeignKey(db_column='relatedTeam', null=True, on_delete=django.db.models.deletion.CASCADE, to='handover.Team')),
                ('related_user', models.ForeignKey(db_column='relatedUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relateduser', to='handover.User')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
