# Generated by Django 2.2 on 2019-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0010_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(db_column='userEmail', max_length=350, unique=True),
        ),
    ]
