# Generated by Django 2.2 on 2019-06-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0011_auto_20190605_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='checkedbyassignee',
            new_name='checkedbyspoc',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='assignedto',
        ),
    ]
