# Generated by Django 2.2.2 on 2019-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0014_auto_20190612_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='resolvedon',
            field=models.DateTimeField(blank=True, db_column='resolvedOn', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='aging_danger',
            field=models.IntegerField(db_column='aging_danger', default=6),
        ),
        migrations.AddField(
            model_name='team',
            name='aging_warn',
            field=models.IntegerField(db_column='aging_warn', default=3),
        ),
    ]
