# Generated by Django 2.2.2 on 2019-06-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0016_remove_handover_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachmentid', models.AutoField(db_column='attachmentid', primary_key=True, serialize=False)),
                ('path', models.TextField(db_column='attachment_path')),
                ('uploaddate', models.DateTimeField(db_column='uploadDate', default=django.utils.timezone.now)),
                ('attachcomment', models.CharField(blank=True, db_column='attachment_comment', max_length=100, null=True)),
                ('handoverid', models.ForeignKey(db_column='handoverId', on_delete=django.db.models.deletion.CASCADE, to='handover.Handover')),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.User')),
            ],
        ),
    ]
